import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import JSZip from 'jszip';
const current = JSON.parse(await readFile('.build/latest.json', 'utf8'));
const embedded = JSON.parse(await readFile(path.join(current.artifact, 'build-manifest.json'), 'utf8'));
const { artifact, ...expected } = current;
assert.deepEqual(embedded, expected);
assert.equal(path.basename(artifact), embedded.id);
const codePaths = (await readdir(path.join(artifact, 'assets'))).filter(file => file.endsWith('.js'));
const code = (await Promise.all(codePaths.map(file => readFile(path.join(artifact, 'assets', file), 'utf8')))).join('\n');
assert.ok(code.includes(embedded.id), 'Compiled game includes the same immutable identity.');
const standalone = await readFile(path.join(artifact, 'Start-Mean-Machine.html'), 'utf8');
assert.ok(standalone.includes(embedded.id));
assert.ok(!/<script\b[^>]*src=/.test(standalone), 'Offline entry has no external script.');
assert.ok(!/<link\b[^>]*rel="stylesheet"/.test(standalone), 'Offline entry has no external stylesheet.');
const zip = await JSZip.loadAsync(await readFile(`${artifact}.zip`));
const archived = await zip.file(`${embedded.id}/build-manifest.json`).async('string');
assert.deepEqual(JSON.parse(archived), embedded);
assert.equal(await zip.file(`${embedded.id}/Start-Mean-Machine.html`).async('string'), standalone);
assert.ok((await readFile('.build/CURRENT_BUILD.md', 'utf8')).includes(embedded.id));
const rows = (await readFile('.build/ledger.jsonl', 'utf8')).trim().split('\n').map(line => JSON.parse(line));
const builds = rows.filter(row => row.status === 'success');
assert.ok(builds.length >= 2, 'At least two actual artifact invocations were verified.');
assert.equal(new Set(builds.map(row => row.id)).size, builds.length);
console.log(`Verified Artifact Identity: ${embedded.id}`);
